---
  # Modified from source: https://github.com/drhelius/travis-ansible-demo/blob/master/travis/test.yml
- hosts: all
  become: yes

  roles:
    - { role: geerlingguy.repo-epel, when: ansible_distribution == "CentOS" }
    - { role: geerlingguy.repo-remi, ansible_distribution == "CentOS" }
    - test_role
